apiVersion: v1
kind: Service
metadata:
  name: {{ template "app-desafio-devops.fullname" . }}
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ template "app-desafio-devops.name" . }}
    chart: {{ template "app-desafio-devops.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.ports.name }}
      protocol: {{ .Values.ports.protocol }}
      name: {{ .Values.ports.name }}
  selector:
    app: {{ template "app-desafio-devops.name" . }}
    release: {{ .Release.Name }}
